### ISSUE TITLE
Error: spawn wmic.exe ENOENT on Windows Server 2025

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/start-server-and-test#398]
Relates to issues:
- https://github.com/indexzero/ps-tree/issues/58
- https://github.com/indexzero/ps-tree/issues/69

## Issue

`start-server-and-test@2.0.9` fails under GitHub Actions `windows-2025` with the error

> Error: spawn wmic.exe ENOENT

`start-server-and-test` depends on `ps-tree`, which depends on the deprecated wmic.

For Microsoft Windows Servers, wmic has been [deprecated since 2016](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831568(v=ws.11)) and it is not installed by default on Windows Server 2025 (see [Features we're no longer developing](https://learn.microsoft.com/en-us/windows-server/get-started/removed-deprecated-features-windows-server-2025#features-were-no-longer-developing)).

The GitHub Actions runner image [windows-2025](https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md) does not include WMIC and there are no plans to add it. (See [Windows Server 2025 is now in public preview](https://github.blog/changelog/2024-12-19-windows-server-2025-is-now-in-public-preview/)).

## Steps to reproduce

Run the following workflow in this repo in GitHub Actions

```yml
name: test-windows-2025
on: workflow_dispatch
jobs:
  tests1:
    runs-on: windows-2025
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Node version 🖨️
        run: node -v

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Run demo 1 📊
        run: npm run demo
```

## Logs

```text
Run npm run demo

> start-server-and-test@0.0.0-development demo
> node src/bin/start.js http://127.0.0.1:9000 message

1: starting server using command "npm run start"
and when url "[ 'http://127.0.0.1:9000' ]" is responding with HTTP status code 200
running tests using command "npm run message"


> start-server-and-test@0.0.0-development start D:\a\start-server-and-test\start-server-and-test
> node test/server.js

sleeping for 5 seconds before starting
listening at port 9000
HEAD

> start-server-and-test@0.0.0-development message D:\a\start-server-and-test\start-server-and-test
> echo Hi there 👋

Hi there 👋
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: spawn wmic.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn wmic.exe',
  path: 'wmic.exe',
  spawnargs: [ 'PROCESS', 'GET', 'Name,ProcessId,ParentProcessId,Status' ]
}

Node.js v22.12.0
Error: Process completed with exit code 1.
```
